from pathlib import Path
import duckdb

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PARQUET_FILE = next(
    (PROJECT_ROOT / "datasets/raw/nyc-taxi").glob("*.parquet")
)

UNSORTED = PROJECT_ROOT / "datasets/raw/nyc-taxi/nyc_stats.parquet"
SORTED = PROJECT_ROOT / "datasets/raw/nyc-taxi/nyc_sorted_stats.parquet"

FILTER_COLUMN = "tpep_pickup_datetime"
ROW_GROUP_SIZE = 100_000

con = duckdb.connect()

print("Input :", PARQUET_FILE)
print("Unsorted:", UNSORTED)
print("Sorted:", SORTED)


# ============================================================
# 1. REWRITE — SAME ORDER, STATISTICS GENERATED BY DUCKDB
# ============================================================

print("\nCreating statistics-enabled unsorted file...")

con.execute(f"""
    COPY (
        SELECT *
        FROM read_parquet('{PARQUET_FILE}')
    )
    TO '{UNSORTED}'
    (
        FORMAT PARQUET,
        COMPRESSION ZSTD,
        ROW_GROUP_SIZE {ROW_GROUP_SIZE}
    )
""")


# ============================================================
# 2. REWRITE — SORTED BY PICKUP DATETIME
# ============================================================

print("Creating sorted file...")

con.execute(f"""
    COPY (
        SELECT *
        FROM read_parquet('{PARQUET_FILE}')
        ORDER BY "{FILTER_COLUMN}"
    )
    TO '{SORTED}'
    (
        FORMAT PARQUET,
        COMPRESSION ZSTD,
        ROW_GROUP_SIZE {ROW_GROUP_SIZE}
    )
""")


# ============================================================
# 3. SHOW ROW-GROUP STATISTICS
# ============================================================

def show_stats(file):
    print("\n" + "=" * 100)
    print(file.name)
    print("=" * 100)

    result = con.execute(f"""
        SELECT
            row_group_id,
            path_in_schema AS column_name,
            stats_min,
            stats_max,
            stats_null_count,
            encodings
        FROM parquet_metadata('{file}')
        WHERE path_in_schema = '{FILTER_COLUMN}'
        ORDER BY row_group_id
    """).df()

    print(result.to_string(index=False))


show_stats(UNSORTED)
show_stats(SORTED)